### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by sunnyyoung** [onevcat/OneV-s-Den#6]
Feed's summary from https://onevcat.com/feed.xml are all empty:

<img width="1158" alt="CleanShot 2020-11-19 at 09 30 48@2x" src="https://user-images.githubusercontent.com/5926284/99608998-fbc67a80-2a49-11eb-949e-82a1d7115922.png">

**Comment by onevcat** [comment]
Fixed in 66a1ec982618777a11d0bb57c40f0eb0c1b5e3ce
